version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:16.3-alpine3.20
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
volumes:
  postgres-db:
    external: false
  