### GET a la pagina de inicio
GET http://localhost:1234/
### POST a la pagina de inicio - dara un 404 - como cualquier otro metodo HTTP
POST http://localhost:1234/

### GET a la pagina de inicio de PERSONA
GET http://localhost:1234/person

### GET a la pagina inicio de PERSONA para obtener por ci
GET http://localhost:1234/person/10918761

### GET a la pagina inicio de PERSONA para obtener por ci
GET http://localhost:1234/person/search/11111112

### POST a la pagina de inicio de PERSONA para crear
POST  http://localhost:1234/person
Content-Type: application/json

{
  "ci" : 10918761,
  "nombres" : "Nestor",
  "paterno" : "Rojas",
  "materno" : "Guarachi",
  "telefono" : "75209039",
  "correo" : "nr@gmail.com",
  "avatar" : "avatarnr"
}

### DELETE para eliminar una persona de la base de datos
DELETE http://localhost:1234/person/10918769

### PATCH a la pagina de inicio de PERSONA para modificar
PATCH http://localhost:1234/person/10918761
Content-Type: application/json

{
  "nombres" : "Nestor2222",
  "paterno" : "Rojas2",
  "materno" : "aa"
}

### GET user page
GET http://localhost:1234/user

### POST user page
POST http://localhost:1234/user
Content-Type: application/json

{
  "person":{
    "ci" : 10918764,
    "nombres" : "Nestor",
    "paterno" : "Rojas",
    "materno" : "Guarachi",
    "telefono" : "75209039",
    "correo" : "nr@gmail.com",
    "avatar" : "avatarnr"
  },
  "user":{
    "usuario":"ignaccio7",
    "pass":"260298nesigABC+-*",
    "rol":"admin"
  }
}

### GET user if forward data
GET http://localhost:1234/user/1


### PATCH user for update data
PATCH http://localhost:1234/user/1
Content-Type: application/json

{
  "usuario":"usuario1",
  "pass":"aA*123456"
}

### POST login user
POST http://localhost:1234/user/login
Content-Type: application/json

{
  "usuario":"usuario1",
  "pass":"260298nesigABC+-*"
}


### AHORA YA ES CON TOKEN ESTE ENDPOINT
### GET a la pagina de inicio de PERSONA con uso de TOKEN
GET http://localhost:1234/person
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiaWduYWNjaW81IiwiaWF0IjoxNzE0MTAxNjIwLCJleHAiOjE3MTQxMDUyMjB9.3XoIePv8zxYPFrrWnTqAM3IlSy08_EhMGUKJ82imDww

### GET a la pagina inicio de PERSONA para obtener por ci
GET http://localhost:1234/person/10918761
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiaWduYWNjaW80IiwiaWF0IjoxNzEwMzc4NzA3fQ.3nQLpJXxK2jtp5o9bPPKdqBicrqOtWQWQ1K1V9X6Xlw

### PATCH a la pagina de inicio de PERSONA para modificar
PATCH http://localhost:1234/person/10918761
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiaWduYWNjaW80IiwiaWF0IjoxNzEwMzc4NzA3fQ.3nQLpJXxK2jtp5o9bPPKdqBicrqOtWQWQ1K1V9X6Xlw
Content-Type: application/json

{
  "nombres" : "Nestor2222",
  "paterno" : "Rojas",
  "materno" : "Guarachi"
}



### GET a la pagina de inicio de NOTAS no publicadas
GET http://localhost:1234/note/

### GET por id 
GET http://localhost:1234/note/17

### POST para crear una NOTA
POST http://localhost:1234/note/
Content-Type: application/json

{
  "usuario_id_usuario": 1,
  "titulo": "titulo11 nuevo",
  "tema": "tema11 nuevo",
  "descripcion": "descripcion11",
  "imagenes": "imagen111123"
}

### DELETE por id 
DELETE http://localhost:1234/note/17

### POST para crear una NOTA
PATCH http://localhost:1234/note/17
Content-Type: application/json

{
  "usuario_id_usuario": 2,
  "titulo": "titulo12 nuevo2",
  "tema": "tema11 nuevo2",
  "descripcion": "descripcion11",
  "imagenes": "imagen111123"
}

### GET a la pagina de inicio de NOTAS no publicadas para filtrar
GET http://localhost:1234/note?titulo=titulo1

### GET a la pagina de inicio de NOTAS no publicadas para filtrar
GET http://localhost:1234/note?titulo=titulo1&tema=tema10

### GET a la pagina de inicio de NOTAS no publicadas para filtrar
GET http://localhost:1234/note?titulo=titulo4&tema=tema&init=2023-02-01&end=2023-05-02

### GET a la pagina de inicio de NOTAS no publicadas para filtrar
GET http://localhost:1234/note?init=2023-02-01&end=2023-07-02



### GET a la pagina de inicio de NOTAS no publicadas prueba PAGINACION
GET http://localhost:1234/note
### GET a la pagina de inicio de NOTAS no publicadas prueba PAGINACION
GET http://localhost:1234/note?page=2
### GET a la pagina de inicio de NOTAS no publicadas prueba PAGINACION
GET http://localhost:1234/note?page=3



### PRUEBA DE VALIDACION DE USUARIO
### admin GET a la pagina de inicio de NOTAS no publicadas prueba PAGINACION
GET http://localhost:1234/note
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjIsInVzZXIiOiJ1c3VhcmlvMiIsImlhdCI6MTcxNTgyNzA3MiwiZXhwIjoxNzE1ODMwNjcyfQ.BnBlNwLv98YZAEc8OVqs7Z2-CkV03WW_SiZaB_tWKwg

### user GET a la pagina de inicio de NOTAS no publicadas prueba PAGINACION
GET http://localhost:1234/note
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiaWduYWNjaW81IiwiaWF0IjoxNzE0NzA1OTg0LCJleHAiOjE3MTQ3MDk1ODR9.-nCbjG7bd0dOrWS6GibjbZQdl0jeDVzR_40D0Y9eAHw


### ------------------------------- PROBANDO PERSONA CON EL FORMA DATA ----------------------------------------

### ------------------------------- PROBANDO USER CON EL FORMA DATA ----------------------------------------

### ------------------------------- PROBANDO NOTE CON EL FORMA DATA ----------------------------------------

### ------------------------------- PROBANDO ACCIONES PARA LOS ARTICULOS ----------------------------------------
### OBTENER TODOS LOS ARTICULOS
GET http://localhost:1234/article

### OBTENER TODOS LOS ARTICULOS
GET http://localhost:1234/article
Content-Type: application/json

{
  "idUser":1
}

### OBTENER UN ARTICULO POR ID
GET http://localhost:1234/article/2

### DAR O QUITAR LIKE A UNA PUBLICACION - puede ser string o number
POST http://localhost:1234/article/like/
Content-Type: application/json

{
  "idPub": "2", 
  "idUser": 3
}

### COMENTAR UNA PUBLICACION 
POST http://localhost:1234/article/comment/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXN1YXJpbzEiLCJpYXQiOjE3MTU5OTI5OTcsImV4cCI6MTcxNTk5NjU5N30._8UuR07XpBhOWjat_-oEvodmNddkkQceQfSfNZg5qz8
Content-Type: application/json

{
  "idPub": "2", 
  "idUser": "3",
  "comment": "Comentario 5333 con el usuario 3"
}

### DESCOMENTAR UNA PUBLICACION 
DELETE http://localhost:1234/article/comment/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXN1YXJpbzEiLCJpYXQiOjE3MTU5OTI5OTcsImV4cCI6MTcxNTk5NjU5N30._8UuR07XpBhOWjat_-oEvodmNddkkQceQfSfNZg5qz8

### MOSTRAR LOS COMENTARIOS - solo se podran ver cuando se ingrese a la publicacion
GET http://localhost:1234/article/comment/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidXN1YXJpbzEiLCJpYXQiOjE3MTU5OTI5OTcsImV4cCI6MTcxNTk5NjU5N30._8UuR07XpBhOWjat_-oEvodmNddkkQceQfSfNZg5qz8