### GET a la pagina de inicio
GET http://localhost:1234/
### POST a la pagina de inicio - dara un 404 - como cualquier otro metodo HTTP
POST http://localhost:1234/

### GET a la pagina de inicio de PERSONA
GET http://localhost:1234/person

### GET a la pagina inicio de PERSONA para obtener por ci
GET http://localhost:1234/person/10918761

### POST a la pagina de inicio de PERSONA para crear
POST  http://localhost:1234/person
Content-Type: application/json

{
  "ci" : 10918761,
  "nombres" : "Nestor",
  "paterno" : "Rojas",
  "materno" : "Guarachi",
  "telefono" : "75209039",
  "correo" : "nr@gmail.com",
  "avatar" : "avatarnr"
}

### DELETE para eliminar una persona de la base de datos
DELETE http://localhost:1234/person/10918769

### PATCH a la pagina de inicio de PERSONA para modificar
PATCH http://localhost:1234/person/10918761
Content-Type: application/json

{
  "nombres" : "Nestor2222",
  "paterno" : "Rojas2",
  "materno" : "aa"
}

### GET user page
GET http://localhost:1234/user

### POST user page
POST http://localhost:1234/user
Content-Type: application/json

{
  "person":{
    "ci" : 10918765,
    "nombres" : "Nestor",
    "paterno" : "Rojas",
    "materno" : "Guarachi",
    "telefono" : "75209039",
    "correo" : "nr@gmail.com",
    "avatar" : "avatarnr"
  },
  "user":{
    "usuario":"ignaccio5",
    "pass":"260298nesigABC+-*",
    "rol":"user"
  }
}

### POST login user
POST http://localhost:1234/user/login
Content-Type: application/json

{
  "usuario":"ignaccio4",
  "pass":"260298nesigABC+-*"
}

### GET a la pagina de inicio de PERSONA con uso de TOKEN
GET http://localhost:1234/person
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiaWduYWNjaW80IiwiaWF0IjoxNzEwMzc4NzA3fQ.3nQLpJXxK2jtp5o9bPPKdqBicrqOtWQWQ1K1V9X6Xlw

### GET a la pagina inicio de PERSONA para obtener por ci
GET http://localhost:1234/person/10918761
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiaWduYWNjaW80IiwiaWF0IjoxNzEwMzc4NzA3fQ.3nQLpJXxK2jtp5o9bPPKdqBicrqOtWQWQ1K1V9X6Xlw