version: '3'

services:
  mysql:
    container_name: mysql-db
    image: mysql:lts-oracle
    environment:
      MYSQL_ROOT_PASSWORD: 260298
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:    
    external: false